# Use root/example as user/password credentials
version: '3.1'

services:
  course_go:
    build: .
    volumes:
      - .:/opt/app/api

  mongo:
    image: mongo
    restart: always
    volumes: 
      - /data/db:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example